@startuml deployment-pos

node "Navigateur Web (Client)" {
  component "Interface utilisateur\n(Vite.js)"
}

node "Serveur Web" {
  component "Backend POS\n(Python - FastAPI)"
  database "Base de données\n(PostgreSQL)" as DB
}

"Interface utilisateur\n(Vite.js)" --> "Backend POS\n(Python - FastAPI)" : HTTP/REST API
"Backend POS\n(Python - FastAPI)" --> DB : ORM (SQLAlchemy)

@enduml
